@set allusersprofile=c:\programdata
@set appdata=c:\users\marti\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=laptop-qp28gb15
@set comspec=c:\windows\system32\cmd.exe
@set configsetroot=c:\windows\configsetroot
@set cplex_studio_binaries127=c:\program files\ibm\ilog\cplex_studio127\opl\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\opl\oplide\;c:\program files\ibm\ilog\cplex_studio127\cplex\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\cpoptimizer\bin\x64_win64
@set cplex_studio_dir127=c:\program files\ibm\ilog\cplex_studio127
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set gdal_data=c:\program files\postgresql\9.6\gdal-data
@set git_home=c:\program files\git
@set gradle_home=c:\program files (x86)\gradle-3.2.1
@set homedrive=c:
@set homepath=\users\marti
@set include=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.14393.0\shared;c:\program files (x86)\windows kits\10\include\10.0.14393.0\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\winrt
@set java_home=c:\program files\java\jdk1.8.0_111
@set lib=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\marti\appdata\local
@set logonserver=\\laptop-qp28gb15
@set m2_home=c:\program files (x86)\apache-maven-3.3.9
@set maven_home=c:\program files (x86)\apache-maven-3.3.9
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set msmpi_bin=c:\program files\microsoft mpi\bin\
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set onedrive=c:\users\marti\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.1;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\windows kits\10\bin\10.0.14393.0\x86;c:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\users\marti\appdata\local\microsoft\visualstudio\15.0_3d29e045\extensions\4salfjqq.j1h\lib\win32\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\vxnfuf2u.fpq\nativebinaries\x86;c:\program files\ibm\ilog\cplex_studio127\opl\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\opl\oplide\;c:\program files\ibm\ilog\cplex_studio127\cplex\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\cpoptimizer\bin\x64_win64;c:\program files\microsoft mpi\bin\;c:\programdata\oracle\java\javapath;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\java\jdk1.8.0_111\bin;c:\program files (x86)\apache-maven-3.3.9\bin;c:\program files\mongodb\server\3.4\bin;c:\program files (x86)\gradle-3.2.1\bin;c:\program files\matlab\r2016b\runtime\win64;c:\program files\matlab\r2016b\bin;c:\program files\matlab\r2016b\polyspace\bin;c:\program files\git\bin;c:\program files\git\cmd;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\anaconda3;c:\program files\anaconda3\scripts;c:\program files\anaconda3\library\bin;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\sbt\bin;c:\program files\dotnet\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files\spark-2.1.0-bin-hadoop2.7;c:\program files (x86)\scala\bin;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\marti\appdata\local\microsoft\windowsapps;c:\program files (x86)\microsoft vs code\bin;c:\users\marti\appdata\local\programs\miktex 2.9\miktex\bin\x64\
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\marti\appdata\local\microsoft\visualstudio\15.0_3d29e045\devenv.exe.config
@set platform=x86
@set postgis_enable_outdb_rasters=1
@set postgis_gdal_enabled_drivers=gtiff png jpeg gif xyz dted usgsdem aaigrid
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 78 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=4e03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community
@set sbt_home=c:\program files (x86)\sbt\
@set sbt_path=c:\program files (x86)\sbt
@set sessionname=console
@set spark_home=c:\program files\spark-2.1.0-bin-hadoop2.7
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\marti\appdata\local\temp
@set tmp=c:\users\marti\appdata\local\temp
@set ucrtversion=10.0.14393.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=laptop-qp28gb15
@set userdomain_roamingprofile=laptop-qp28gb15
@set username=marti
@set userprofile=c:\users\marti
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.10.25017\
@set visualstudiodir=c:\users\marti\onedrive\documenti\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.0.26228.12
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1036
@set vssdk150install=c:\program files (x86)\microsoft visual studio\2017\community\vssdk
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.14393.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.14393.0\
@set windowssdkversion=10.0.14393.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\users\marti\appdata\local\microsoft\visualstudio\15.0_3d29e045\extensions\4salfjqq.j1h\lib\win32\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\extensions\vxnfuf2u.fpq\nativebinaries\x86;c:\program files\ibm\ilog\cplex_studio127\opl\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\opl\oplide\;c:\program files\ibm\ilog\cplex_studio127\cplex\bin\x64_win64;c:\program files\ibm\ilog\cplex_studio127\cpoptimizer\bin\x64_win64;c:\program files\microsoft mpi\bin\;c:\programdata\oracle\java\javapath;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\java\jdk1.8.0_111\bin;c:\program files (x86)\apache-maven-3.3.9\bin;c:\program files\mongodb\server\3.4\bin;c:\program files (x86)\gradle-3.2.1\bin;c:\program files\matlab\r2016b\runtime\win64;c:\program files\matlab\r2016b\bin;c:\program files\matlab\r2016b\polyspace\bin;c:\program files\git\bin;c:\program files\git\cmd;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\anaconda3;c:\program files\anaconda3\scripts;c:\program files\anaconda3\library\bin;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\sbt\bin;c:\program files\dotnet\;c:\program files\miktex 2.9\miktex\bin\x64\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files\spark-2.1.0-bin-hadoop2.7;c:\program files (x86)\scala\bin;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\users\marti\appdata\local\microsoft\windowsapps;c:\program files (x86)\microsoft vs code\bin;c:\users\marti\appdata\local\programs\miktex 2.9\miktex\bin\x64\

@call cl.exe